name: Simple Sync
description: Synchronize files with the specific branch
inputs:
  ref:
    description: Base ref
    default: main
    required: true
  files:
    description: Synchronized files and directories
    required: true
runs:
  using: composite
  steps:
    - run: |
        echo "::error::inpput 'ref' is required"
        exit 1
      shell: bash
      if: inputs.ref == ''
    - run: |
        echo "::error::inpput 'files' is required"
        exit 1
      shell: bash
      if: inputs.files == ''

    - run: echo "path=.simple-sync-action-$GITHUB_SHA" >> "$GITHUB_OUTPUT"
      shell: bash
      id: src

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        ref: ${{inputs.ref}}
        path: ${{steps.src.outputs.path}}

    - run: |
        set -euo pipefail
        while read -r line; do
          rsync --delete -av "$line" "../$line"
        done < <(echo "$FILES" | grep -v -E '^\s*$' | grep -v -E '^#')
      shell: bash
      working-directory: ${{steps.src.outputs.path}}
      env:
        FILES: ${{inputs.files}}

    - run: rm -Rf "$SRC"
      shell: bash
      env:
        SRC: ${{steps.src.outputs.path}}
